Cherry pick of e5348d5a69daef843de3532adb7be4e34d597b3c failed
stdout:

stderr:
error: could not apply e5348d5a69d... [FIX] website_sale_stock: allow override of context
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'