Cherry pick of 49c982d9fc66074b507bb689850732084e483a41 failed
stdout:

stderr:

Error: could not apply 49c982d9fc6... [FIX] payment_stripe_sca: better error handling
Hint: after resolving the conflicts, mark the corrected paths
Hint: with 'git add <paths>' or 'git rm <paths>'
Hint: and commit the result with 'git commit'
X-original-commit: aad565c9ff0345bdbadfb268ffc1828e7c3e5588